/**
 * This script counts the number of spots of different classes per cells 
 * (spots should be PointsROI objects, ideally generated by spotiflow).
 * 
 * The number of spots of each class is added a measurement to the corresonding cell.
 * 
 * Assumptions
 *     - all spots are assigned to a class (this can be achieve by activating 
 *     'setClassChannelName()' in the qupath extension spotiflow builder.
 *     - Resolve hierarchy should be done prior to run the script. If you are using spotiflow extension,
 *      cellpose, stardist, or instanseg extension, hierarchy is already resolved.
 * 
 * 
 * author: Rémy Dornier - PTBIOP & Claude.ai
 * date: 2025-05.29
 * version: 1.0.0
 * 
 * Last tested on QuPath 0.7.x
 * 
 * -----------------------------------------------------------------------------
 * Copyright (c) 2026 ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE, Switzerland, BioImaging And Optics Platform (BIOP)
 * All rights reserved.
 * 
 * Licensed under the BSD-3-Clause License:
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided 
 * that the following conditions are met:
 * 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer 
 *    in the documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products 
 *     derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, 
 * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF 
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * -----------------------------------------------------------------------------
 * 
 */


/***********************
 * VARIABLES TO MODIFY
 ***********************/


def TISSUE_CLASS = "tissue"


/***********************
 * BEGINNING OF THE SCRIPT
 ***********************/
 

def imageData = getCurrentImageData()
def hierarchy = imageData.getHierarchy()

// getting selected annotation or tissue annotations
def selectedObjects = getSelectedObjects()
def tissueAnnotations = []
if(selectedObjects.isEmpty()) {
    tissueAnnotations = getAnnotationObjects().findAll{ it.getPathClass() == getPathClass(TISSUE_CLASS) }
}else{
    tissueAnnotations = selectedObjects.findAll{ it.isAnnotation()}
}
 

if(tissueAnnotations.isEmpty()) {
    Logger.warn("No annotation selected and no annotation of class tissue.")
    Logger.warn("Please select an annotation or assign it(them) the class 'tissue'")
    println "Script stopped"
    return
}


tissueAnnotations.each{obj ->

    // getting cells and spots
    def cells  = obj.getChildObjects().findAll { it.isCell() }
    if(cells.isEmpty()){
        cells  = obj.getChildObjects().findAll { it.isDetection() && it.getROI() instanceof  PolygonROI}
    }
    def spots  = obj.getChildObjects().findAll { it.isDetection() && it.getROI() instanceof  PointsROI}
    println "Cells: " + cells.size() + ", Spots: " + spots.size()
    
    
    // Cache cell geometries and build STRtree
    println "Building the cell geometries tree..."
    def tree = new STRtree()
    def cellGeoms = new HashMap<PathObject, org.locationtech.jts.geom.Geometry>()
    cells.each { c ->
        def g = c.getROI().getGeometry()
        cellGeoms[c] = g
        tree.insert(g.getEnvelopeInternal(), c)
    }
    tree.build()   // MUST be called before concurrent queries
    
    
    // getting classes and class index
    println "Getting spot classes..."
    def classList = spots*.getPathClass().unique()
    def classIndex = [:]
    classList.eachWithIndex { cls, i -> classIndex[cls] = i }
    int nClasses = classList.size()
    println "Spot classes (" + nClasses + "): " + classList*.toString()
    
    
    //Concurrent accumulator: cell -> LongAdder[nClasses]
    def counts = new ConcurrentHashMap<PathObject, LongAdder[]>()
    def gf = cellGeoms.values().iterator().next().getFactory()
    def matched   = new LongAdder()
    def totalsPerClass  = new AtomicIntegerArray(nClasses)
    def processed = new AtomicInteger(0)
    def meanIntensities = new ConcurrentHashMap<PathObject, LongAdder[]>()
    
    
    // Parallel query
    // Getting the cell which convers the current point centroid
    // and increment the number of spot for that cell for the current spot class
    println "Starting cell <> spots assignment..."
    spots.parallelStream().forEach { s ->
        def roi = s.getROI()
        def pt = gf.createPoint(new Coordinate(roi.getCentroidX(), roi.getCentroidY()))
        def candidates = tree.query(pt.getEnvelopeInternal())
    
        for (cand in candidates) {
            def cell = cand as PathObject
            if (cellGeoms[cell].covers(pt)) {
                def arr = counts.computeIfAbsent(cell, { k ->
                    def a = new LongAdder[nClasses]
                    for (int i = 0; i < nClasses; i++) a[i] = new LongAdder()
                    a
                })
                def mean = meanIntensities.computeIfAbsent(cell, { k ->
                    def a = new LongAdder[nClasses]
                    for (int i = 0; i < nClasses; i++) a[i] = new LongAdder()
                    a
                })
                int idx = classIndex[s.getPathClass()]
                arr[idx].increment()
                mean[idx].add((long)(s.getMeasurements().get("Spotiflow intensity")*100))
                totalsPerClass.incrementAndGet(idx) 
                matched.increment()
                s.getMetadata().put("Parent cell", String.valueOf(cell.getID()))
                break   // assume a spot belongs to a single cell
            }
        }
    
        int n = processed.incrementAndGet()
        if (n % 100000 == 0) println "  processed " + n + " spots"
    }
   
   
    def assignedSpotsPerClass = new int[nClasses]
    def unassignedSpotsPerClass = new int[nClasses]
    
    println "--- Summary per class ---"
    println String.format("%-25s %12s %12s %12s", "Class", "Total", "Assigned", "Unassigned")
    int totalAll = 0, assignedAll = 0
    for (int i = 0; i < nClasses; i++) {
        def total = spots.findAll{it.getPathClass().equals(classList[i])}.size()
        int assigned   = totalsPerClass.get(i)
        int unassigned = total - assigned
        assignedSpotsPerClass[i] = assigned
        unassignedSpotsPerClass[i] = unassigned
        totalAll     += total
        assignedAll  += assigned
        def name = classList[i]?.toString() ?: 'Unclassified'
        println String.format("%-25s %12d %12d %12d", name, total, assigned, unassigned)
    }
    println String.format("%-25s %12d %12d %12d",
            "TOTAL", totalAll, assignedAll, totalAll - assignedAll)
    println "matched (sanity): ${matched.sum()}"
    
    
    // 4. Write measurements
    println "Adding spots count for each cell..."
    cells.each { c ->
        def ml = c.getMeasurements()
        def arr = counts.get(c)
        def mean = meanIntensities.get(c)
        classList.eachWithIndex { cls, i ->
            def pathClass = cls?.toString() ?: 'Unclassified'
            def name = "Spots: " + pathClass
            double v = (arr == null) ? 0d : arr[i].sum() as double
            double m = (mean == null || v == 0d) ? 0d : mean[i].sum() / v / 100 as double
            ml.put(name, v)
            def name2 = name + ": Mean"
            ml.put(name2, m)
        }
    }
    
    
    def objMl = obj.getMeasurements()
    for (int i = 0; i < nClasses; i++) {
        objMl.put("Num spots assigned:"+classList[i].toString(), assignedSpotsPerClass[i])
        objMl.put("Num spots unassigned:"+classList[i].toString(), unassignedSpotsPerClass[i])
    }
}

fireHierarchyUpdate()
println "End of the script."


/***********************
 * IMPORTS
 ***********************/
 
 
import org.locationtech.jts.index.strtree.STRtree
import org.locationtech.jts.geom.Coordinate
import qupath.lib.objects.PathObject
import qupath.lib.roi.PointsROI
import qupath.lib.roi.PolygonROI
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.LongAdder
import java.util.concurrent.atomic.AtomicInteger
import java.util.concurrent.atomic.AtomicIntegerArray